## Numpy Library Exercises

In [2]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [3]:
import random
random.seed(42)
random_array = np.array(random.sample(range(0, 10), 10))
result = np.where((random_array > 3) & (random_array < 8), -random_array, random_array)
print(result)

[ 1  0 -4  9 -6 -5  8  2  3 -7]


**2.** Replace the maximum element of a random array with 0

In [4]:
result = np.where(random_array == np.max(random_array), 0, random_array)
print(result)

[1 0 4 0 6 5 8 2 3 7]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [5]:
# cartesian product
def direct_product(arr):
    return np.array(np.meshgrid(*arr)).T.reshape(-1, len(arr))

a1 = np.array([1, 2])
a2 = np.array([3, 4])
direct_product([a1, a2])

array([[1, 3],
       [1, 4],
       [2, 3],
       [2, 4]])

**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])
B = np.array([[1, 2], [3, 1]])
# rows_a, rows_b, elements_a, elements_b
matches = np.array([A[:, None,:, None] == B[None, :, None, :]]).all(axis=0)
print(matches.shape) # (8, 2, 3, 2) - (8 rows in A, 2 rows in B, 3 columns in A, 2 columns in B)
found_elements = matches.any(axis=2)
found_rows_b = found_elements.all(axis=2)
final_mask = found_rows_b.all(axis=1)
result = A[final_mask]
print(result)

(8, 2, 3, 2)
[[1 2 3]]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [7]:
# math way: if all elements in a raw are equal, then the diff between max and min = 0.
M = np.array([[1, 2, 3],
              [4, 4, 4],
              [5, 6, 7],
              [8, 8, 8],
              [9, 10, 11],
              [12, 12, 12],
              [13, 14, 15],
              [16, 16, 16],
              [17, 18, 19],
              [20, 20, 20]])
r_min = M.min(axis=1)
r_max = M.max(axis=1)
mask = r_min != r_max
result = M[mask]
print(result)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [8]:
#Broadcast way: comparing all elements in a row with the first element.
first_col = M[:,0,None]
result =  ~(first_col == M).all(axis=1)
print(M[result])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [9]:
A = np.array([[1, 2, 3],
              [10, 11, 12],
              [1, 2, 3], #duplicate
              [7, 8, 9],
              [4, 5, 6],
              [4, 5, 6]]) #duplicate
result, indexes = np.unique(A, axis=0, return_index=True)
print(f'sorted:\n {result}')
print(f'original order:\n {A[np.sort(indexes)]}')


sorted:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
original order:
 [[ 1  2  3]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [10]:
# python
from math import prod
X = [[1, 0, 1],
     [2, 0, 2],
     [3, 0, 3],
     [4, 4, 4]]

n = min(len(X), len(X[0])) # размер диагонали = минимальному значению между количеством строк и столбцов
diag = [X[i][j] for i in range(n) for j in range(n) if i == j and X[i][j] != 0]
print(f"python: {prod(diag)}")
# numpy
diag = np.diag(X)
result = np.prod(diag[diag != 0])
print(f"numpy: {result}")

python: 3
numpy: 3


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [11]:
#Python
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
result = sorted(x) == sorted(y)
print(f"python: {result}")

#Numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
result = np.array_equal(np.sort(x), np.sort(y))
print(f"numpy: {result}")

python: True
numpy: True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [12]:
# python

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
candidates = [next_el for curr_el, next_el in zip(x[:-1], x[1:]) if curr_el == 0]
max(candidates)

#numpy
X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = X[:-1] == 0
X[1:][mask].max()

np.int64(5)

* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [13]:
# python
from itertools import groupby
x = [2, 2, 2, 3, 3, 3, 5]
values = []
counts = []
for value, group in groupby(x):
    values.append(value)
    counts.append(len(list(group)))

print(f"python: {values}, {counts}")

#numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
split_indices = np.where(x[1:] != x[:-1])[0] + 1
boundaries = np.concatenate(([0], split_indices, [len(x)]))
values_numpy = x[boundaries[:-1]]
counts_numpy = np.diff(boundaries)

print(f"Числа: {values_numpy}")
print(f"Повторения: {counts_numpy}")



python: [2, 3, 5], [3, 3, 1]
Числа: [2 3 5]
Повторения: [3 3 1]


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [28]:
import math
from scipy.spatial.distance import cdist
import time
X = [[0, 0], [1, 1], [2, 2]]
Y = [[3, 3], [4, 4]]

def python_distance(X, Y):
    result_matrix = []
    for i in range(len(X)):
        row_distances = []
        for j in range(len(Y)):
            sum_sq = 0
            for k in range(len(X[0])):
                sum_sq += (X[i][k] - Y[j][k]) ** 2
            row_distances.append(math.sqrt(sum_sq))
        result_matrix.append(row_distances)
    return result_matrix

print("Python:")
for row in python_distance(X, Y):
    print(row)

X_np = np.array([[0, 0], [1, 1], [2, 2]])
Y_np = np.array([[3, 3], [4, 4]])

def numpy_distance(X, Y):
    # 1. Вычитаем с помощью бродкастинга
    diff = X[:, None, :] - Y[None, :, :] # Форма (3, 2, 2)

    # 2. Возводим в квадрат
    sq_diff = diff ** 2

    # 3. Суммируем координаты (сворачиваем axis=2) и извлекаем корень
    dist = np.sqrt(sq_diff.sum(axis=2))  # Форма (3, 2)
    return dist

print("\nnumpy:")
print(numpy_distance(X_np, Y_np))


N, M, D = 1000, 1000, 50
X_np = np.random.rand(N, D)
Y_np = np.random.rand(M, D)

X_list = X_np.tolist()
Y_list = Y_np.tolist()

start = time.time()
dist_scipy = cdist(X_np, Y_np)
time_scipy = time.time() - start

start = time.time()
diff = X_np[:, None, :] - Y_np[None, :, :]
dist_numpy = np.sqrt(np.sum(diff ** 2, axis=2))
time_numpy = time.time() - start

start = time.time()
dist_python = python_distance(X_list, Y_list)
time_python = time.time() - start

print(f"Время SciPy:      {time_scipy:.4f} сек")
print(f"Время NumPy:      {time_numpy:.4f} сек")
print(f"Время Python:     {time_python:.4f} сек")

Python:
[4.242640687119285, 5.656854249492381]
[2.8284271247461903, 4.242640687119285]
[1.4142135623730951, 2.8284271247461903]

numpy:
[[4.24264069 5.65685425]
 [2.82842712 4.24264069]
 [1.41421356 2.82842712]]
Время SciPy:      0.0153 сек
Время NumPy:      0.1217 сек
Время Python:     4.6889 сек


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [15]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [16]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [30]:
average_calories = np.mean(calorie_stats)
print(f"Average calories of competitors: {average_calories}")
print(f"Difference from CrunchieMunchies: {average_calories - 60}")

Average calories of competitors: 106.88311688311688
Difference from CrunchieMunchies: 46.883116883116884


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [31]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [32]:
median_calories = np.median(calorie_stats)
median_calories

np.float64(110.0)

5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [36]:
nth_percentile = None
for percentile in range(0, 101, 1):
    value = np.percentile(calorie_stats, percentile)
    print(f"{percentile}th percentile: {value}")
    if value > 60:
        nth_percentile = percentile
        break
print(f"The lowest percentile that exceeds 60 calories is: {nth_percentile}th percentile")

0th percentile: 50.0
1th percentile: 50.0
2th percentile: 50.0
3th percentile: 55.599999999999994
4th percentile: 70.0
The lowest percentile that exceeds 60 calories is: 4th percentile


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [39]:
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100
print(more_calories)

96.1038961038961


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [40]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

CrunchieMunchies has a clear calorie advantage over competing cereals. The average competitor is around 106 calories, and even with normal variation (about ±19 calories), most cereals are still much higher than CrunchieMunchies at 60 calories.